[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"

# Fjerner plugins-seksjonen som kan forårsake syntaksproblemer
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

# Forenkler redirects-seksjonen
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
