[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"

# Aktiverer Netlify Next.js plugin igjen, men med riktig syntaks
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Fjerner unødvendig redirect som kan forårsake problemer
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
